<a href="https://colab.research.google.com/github/sonos4849-a11y/-DecodeLabs-Internship./blob/main/project_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import files

uploaded = files.upload()

for fn in uploaded.keys():
  print('User uploaded file "{name}" with length {length} bytes'.format(
      name=fn, length=len(uploaded[fn])))

Saving Dataset for Data Analytics.xlsx to Dataset for Data Analytics.xlsx
User uploaded file "Dataset for Data Analytics.xlsx" with length 105267 bytes

In [ ]:

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [ ]:
df = pd.read_excel('Dataset for Data Analytics.xlsx')
df.head()

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice
0,ORD200000,2023-01-04,C72649,Monitor,5,570.62,928 Main St,Debit Card,Shipped,TRK37947903,7,SAVE10,Instagram,2853.10
1,ORD200001,2024-08-23,C75739,Phone,2,151.35,823 Main St,Online,Shipped,TRK91186779,3,SAVE10,Referral,302.70
2,ORD200002,2024-02-27,C81728,Tablet,5,550.68,512 Main St,Credit Card,Cancelled,TRK42903982,8,FREESHIP,Email,2753.40
3,ORD200003,2023-10-15,C33540,Chair,1,273.19,275 Main St,Debit Card,Returned,TRK62788070,5,SAVE10,Facebook,273.19
4,ORD200004,2025-05-08,C81840,Printer,4,626.01,668 Main St,Online,Delivered,TRK29241424,8,SAVE10,Email,2504.04

In [ ]:
df.head(10)

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice
0,ORD200000,2023-01-04,C72649,Monitor,5,570.62,928 Main St,Debit Card,Shipped,TRK37947903,7,SAVE10,Instagram,2853.10
1,ORD200001,2024-08-23,C75739,Phone,2,151.35,823 Main St,Online,Shipped,TRK91186779,3,SAVE10,Referral,302.70
2,ORD200002,2024-02-27,C81728,Tablet,5,550.68,512 Main St,Credit Card,Cancelled,TRK42903982,8,FREESHIP,Email,2753.40
3,ORD200003,2023-10-15,C33540,Chair,1,273.19,275 Main St,Debit Card,Returned,TRK62788070,5,SAVE10,Facebook,273.19
4,ORD200004,2025-05-08,C81840,Printer,4,626.01,668 Main St,Online,Delivered,TRK29241424,8,SAVE10,Email,2504.04
5,ORD200005,2023-10-23,C37249,Phone,2,245.86,934 Main St,Credit Card,Shipped,TRK72976927,4,SAVE10,Instagram,491.72
6,ORD200006,2025-06-17,C83492,Laptop,1,664.42,986 Main St,Gift Card,Returned,TRK96417362,6,SAVE10,Facebook,664.42
7,ORD200007,2023-05-12,C41460,Monitor,5,149.55,706 Main St,Cash,Shipped,TRK78809193,9,FREESHIP,Facebook,747.75
8,ORD200008,2025-04-02,C26817,Phone,2,134.28,904 Main St,Gift Card,Cancelled,TRK61042692,2,NaN,Email,268.56
9,ORD200009,2023-11-21,C31946,Desk,4,509.38,102 Main St,Credit Card,Shipped,TRK33478363,6,SAVE10,Google,2037.52

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   OrderID          1200 non-null   object
 1   Date             1200 non-null   datetime64[ns]
 2   CustomerID       1200 non-null   object
 3   Product          1200 non-null   object
 4   Quantity         1200 non-null   int64
 5   UnitPrice        1200 non-null   float64
 6   ShippingAddress  1200 non-null   object
 7   PaymentMethod    1200 non-null   object
 8   OrderStatus      1200 non-null   object
 9   TrackingNumber   1200 non-null   object
 10  ItemsInCart      1200 non-null   int64
 11  CouponCode       891 non-null    object
 12  ReferralSource   1200 non-null   object
 13  TotalPrice       1200 non-null   float64
dtypes: datetime64[ns](1), float64(2), int64(2), object(9)
memory usage: 131.4+ KB

In [ ]:
# count missing values in each column
missing_values = df.isnull().sum()
# check missing values (True/False)
print(df.isna())
# total missing values
print(df.isna().sum().sum())

      OrderID   Date  CustomerID  Product  Quantity  UnitPrice  \
0       False  False       False    False     False      False
1       False  False       False    False     False      False
2       False  False       False    False     False      False
3       False  False       False    False     False      False
4       False  False       False    False     False      False
...       ...    ...         ...      ...       ...        ...
1195    False  False       False    False     False      False
1196    False  False       False    False     False      False
1197    False  False       False    False     False      False
1198    False  False       False    False     False      False
1199    False  False       False    False     False      False

      ShippingAddress  PaymentMethod  OrderStatus  TrackingNumber  \
0               False          False        False           False
1               False          False        False           False
2               False          False        False           False
3               False          False        False           False
4               False          False        False           False
...               ...            ...          ...             ...
1195            False          False        False           False
1196            False          False        False           False
1197            False          False        False           False
1198            False          False        False           False
1199            False          False        False           False

      ItemsInCart  CouponCode  ReferralSource  TotalPrice
0           False       False           False       False
1           False       False           False       False
2           False       False           False       False
3           False       False           False       False
4           False       False           False       False
...           ...         ...             ...         ...
1195        False       False           False       False
1196        False        True           False       False
1197        False       False           False       False
1198        False       False           False       False
1199        False       False           False       False

[1200 rows x 14 columns]
309

In [ ]:
# remove rows with any missing values
df_clean = df.dropna()

# OR remove columns with any missing values
# df_clean = df.dropna(axis=1)

# save cleaned data
df_clean.to_excel("cleaned_data.xlsx", index=False)

print(df_clean)

        OrderID       Date CustomerID  Product  Quantity  UnitPrice  \
0     ORD200000 2023-01-04     C72649  Monitor         5     570.62
1     ORD200001 2024-08-23     C75739    Phone         2     151.35
2     ORD200002 2024-02-27     C81728   Tablet         5     550.68
3     ORD200003 2023-10-15     C33540    Chair         1     273.19
4     ORD200004 2025-05-08     C81840  Printer         4     626.01
...         ...        ...        ...      ...       ...        ...
1194  ORD201194 2023-11-19     C29885  Printer         3     189.44
1195  ORD201195 2024-06-20     C21126     Desk         1     107.04
1197  ORD201197 2023-07-13     C79674   Tablet         2     436.84
1198  ORD201198 2024-08-22     C64753    Chair         4     262.52
1199  ORD201199 2023-06-11     C57502   Tablet         4     560.58

     ShippingAddress PaymentMethod OrderStatus TrackingNumber  ItemsInCart  \
0        928 Main St    Debit Card     Shipped    TRK37947903            7
1        823 Main St        Online     Shipped    TRK91186779            3
2        512 Main St   Credit Card   Cancelled    TRK42903982            8
3        275 Main St    Debit Card    Returned    TRK62788070            5
4        668 Main St        Online   Delivered    TRK29241424            8
...              ...           ...         ...            ...          ...
1194     725 Main St          Cash     Pending    TRK62067865            4
1195     392 Main St   Credit Card   Cancelled    TRK38009181            6
1197     275 Main St        Online   Delivered    TRK88039356            2
1198     509 Main St    Debit Card   Cancelled    TRK71683331            4
1199     201 Main St     Gift Card    Returned    TRK51116746            6

     CouponCode ReferralSource  TotalPrice
0        SAVE10      Instagram     2853.10
1        SAVE10       Referral      302.70
2      FREESHIP          Email     2753.40
3        SAVE10       Facebook      273.19
4        SAVE10          Email     2504.04
...         ...            ...         ...
1194   FREESHIP          Email      568.32
1195   FREESHIP         Google      107.04
1197   FREESHIP      Instagram      873.68
1198   WINTER15      Instagram     1050.08
1199     SAVE10       Referral     2242.32

[891 rows x 14 columns]

In [ ]:
df.shape

(1200, 14)

In [ ]:
pd.isnull(df).sum()

OrderID              0
Date                 0
CustomerID           0
Product              0
Quantity             0
UnitPrice            0
ShippingAddress      0
PaymentMethod        0
OrderStatus          0
TrackingNumber       0
ItemsInCart          0
CouponCode         309
ReferralSource       0
TotalPrice           0
dtype: int64

In [ ]:
# remove rows with any missing values
df_clean = df.dropna()

# OR remove columns with any missing values
# df_clean = df.dropna(axis=1)

# save cleaned data
df_clean.to_excel("cleaned_data.xlsx", index=False)

print(df_clean)

        OrderID       Date CustomerID  Product  Quantity  UnitPrice  \
0     ORD200000 2023-01-04     C72649  Monitor         5     570.62
1     ORD200001 2024-08-23     C75739    Phone         2     151.35
2     ORD200002 2024-02-27     C81728   Tablet         5     550.68
3     ORD200003 2023-10-15     C33540    Chair         1     273.19
4     ORD200004 2025-05-08     C81840  Printer         4     626.01
...         ...        ...        ...      ...       ...        ...
1194  ORD201194 2023-11-19     C29885  Printer         3     189.44
1195  ORD201195 2024-06-20     C21126     Desk         1     107.04
1197  ORD201197 2023-07-13     C79674   Tablet         2     436.84
1198  ORD201198 2024-08-22     C64753    Chair         4     262.52
1199  ORD201199 2023-06-11     C57502   Tablet         4     560.58

     ShippingAddress PaymentMethod OrderStatus TrackingNumber  ItemsInCart  \
0        928 Main St    Debit Card     Shipped    TRK37947903            7
1        823 Main St        Online     Shipped    TRK91186779            3
2        512 Main St   Credit Card   Cancelled    TRK42903982            8
3        275 Main St    Debit Card    Returned    TRK62788070            5
4        668 Main St        Online   Delivered    TRK29241424            8
...              ...           ...         ...            ...          ...
1194     725 Main St          Cash     Pending    TRK62067865            4
1195     392 Main St   Credit Card   Cancelled    TRK38009181            6
1197     275 Main St        Online   Delivered    TRK88039356            2
1198     509 Main St    Debit Card   Cancelled    TRK71683331            4
1199     201 Main St     Gift Card    Returned    TRK51116746            6

     CouponCode ReferralSource  TotalPrice
0        SAVE10      Instagram     2853.10
1        SAVE10       Referral      302.70
2      FREESHIP          Email     2753.40
3        SAVE10       Facebook      273.19
4        SAVE10          Email     2504.04
...         ...            ...         ...
1194   FREESHIP          Email      568.32
1195   FREESHIP         Google      107.04
1197   FREESHIP      Instagram      873.68
1198   WINTER15      Instagram     1050.08
1199     SAVE10       Referral     2242.32

[891 rows x 14 columns]

In [ ]:
# remove duplicate rows
df_no_duplicates = df.drop_duplicates()
duplicate_count = df.duplicated().sum()
print("Total duplicate rows",duplicate_count)




print(df_no_duplicates)

Total duplicate rows 0
        OrderID       Date CustomerID  Product  Quantity  UnitPrice  \
0     ORD200000 2023-01-04     C72649  Monitor         5     570.62
1     ORD200001 2024-08-23     C75739    Phone         2     151.35
2     ORD200002 2024-02-27     C81728   Tablet         5     550.68
3     ORD200003 2023-10-15     C33540    Chair         1     273.19
4     ORD200004 2025-05-08     C81840  Printer         4     626.01
...         ...        ...        ...      ...       ...        ...
1195  ORD201195 2024-06-20     C21126     Desk         1     107.04
1196  ORD201196 2024-03-04     C20095  Monitor         2     662.53
1197  ORD201197 2023-07-13     C79674   Tablet         2     436.84
1198  ORD201198 2024-08-22     C64753    Chair         4     262.52
1199  ORD201199 2023-06-11     C57502   Tablet         4     560.58

     ShippingAddress PaymentMethod OrderStatus TrackingNumber  ItemsInCart  \
0        928 Main St    Debit Card     Shipped    TRK37947903            7
1        823 Main St        Online     Shipped    TRK91186779            3
2        512 Main St   Credit Card   Cancelled    TRK42903982            8
3        275 Main St    Debit Card    Returned    TRK62788070            5
4        668 Main St        Online   Delivered    TRK29241424            8
...              ...           ...         ...            ...          ...
1195     392 Main St   Credit Card   Cancelled    TRK38009181            6
1196     778 Main St        Online   Cancelled    TRK69207593            5
1197     275 Main St        Online   Delivered    TRK88039356            2
1198     509 Main St    Debit Card   Cancelled    TRK71683331            4
1199     201 Main St     Gift Card    Returned    TRK51116746            6

     CouponCode ReferralSource  TotalPrice
0        SAVE10      Instagram     2853.10
1        SAVE10       Referral      302.70
2      FREESHIP          Email     2753.40
3        SAVE10       Facebook      273.19
4        SAVE10          Email     2504.04
...         ...            ...         ...
1195   FREESHIP         Google      107.04
1196        NaN       Facebook     1325.06
1197   FREESHIP      Instagram      873.68
1198   WINTER15      Instagram     1050.08
1199     SAVE10       Referral     2242.32

[1200 rows x 14 columns]

data format

In [ ]:
df['TotalPrice'] = df['TotalPrice'].astype('int')

In [ ]:
df['TotalPrice'].dtypes

dtype('int64')

In [ ]:
df['UnitPrice'] = df['UnitPrice'].astype('int')

In [ ]:
df['UnitPrice'].dtypes

dtype('int64')

In [ ]:
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
1195    False
1196    False
1197    False
1198    False
1199    False
Length: 1200, dtype: bool